import "@hotwired/turbo-rails"
import "./add_jquery"
import "./controllers"
import "./custom/preview"
import "./custom/default_values"
import "./custom/number-input"
import "./custom/top_bubble"
import "./custom/bubble"
import "./custom/search"
import "./custom/tourguide"
import "trix"
import "@rails/actiontext"
import "../../assets/javascripts/serviceworker-companion"

Turbo.session.drive = false;