// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
import "./add_jquery"
import "./controllers"
import "./custom/preview"
import "./custom/default_values"
import "./custom/range_slider"
import "./custom/top_bubble"
import "./custom/bubble"
import "trix"
import "@rails/actiontext"
